name: fp5300
channels:
  - defaults
  - conda-forge
  - https://repo.anaconda.com/pkgs/main
  - https://repo.anaconda.com/pkgs/r
dependencies:
  - anyio=4.11.0=pyhcf101f3_0
  - aom=3.9.1=h7bae524_0
  - appnope=0.1.4=py312hca03da5_0
  - argon2-cffi=21.3.0=pyhd3eb1b0_0
  - argon2-cffi-bindings=25.1.0=py312h254cc4a_0
  - asttokens=3.0.0=py312hca03da5_0
  - async-lru=2.0.5=py312hca03da5_0
  - attrs=25.4.0=py312hca03da5_0
  - av=13.1.0=py312h117057c_0
  - babel=2.16.0=py312hca03da5_0
  - backports=1.0=pyhd8ed1ab_5
  - backports.tarfile=1.2.0=pyhd8ed1ab_1
  - beautifulsoup4=4.14.2=pyha770c72_0
  - bleach=6.2.0=py312hca03da5_0
  - brotli-python=1.2.0=py312hcae0c51_0
  - bzip2=1.0.8=hd037594_8
  - ca-certificates=2025.11.4=hca03da5_0
  - cachecontrol=0.14.3=pyha770c72_0
  - cachecontrol-with-filecache=0.14.3=pyhd8ed1ab_0
  - cairo=1.18.4=h6a3b0d2_0
  - certifi=2025.11.12=py312hca03da5_0
  - cffi=2.0.0=py312h1b4d9a2_1
  - charset-normalizer=3.4.4=pyhd8ed1ab_0
  - cleo=2.1.0=pyhd8ed1ab_1
  - click=8.3.0=pyh707e725_0
  - cloup=3.0.8=pyhd8ed1ab_0
  - colorama=0.4.6=pyhd8ed1ab_1
  - comm=0.2.1=py312hca03da5_0
  - contourpy=1.3.1=py312h48ca7d4_0
  - crashtest=0.4.1=pyhd8ed1ab_1
  - cycler=0.11.0=pyhd3eb1b0_0
  - cython=3.1.6=py312h6868a3c_0
  - dav1d=1.2.1=hb547adb_0
  - dbus=1.16.2=hda038a8_0
  - debugpy=1.8.16=py312h0962b89_0
  - decorator=5.2.1=pyhd8ed1ab_0
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - distlib=0.4.0=pyhd8ed1ab_0
  - dulwich=0.22.8=py312hcd83bfe_0
  - exceptiongroup=1.3.0=pyhd8ed1ab_0
  - executing=2.2.1=py312hca03da5_0
  - ffmpeg=7.1.1=gpl_h670d5b4_111
  - filelock=3.20.0=pyhd8ed1ab_0
  - findpython=0.6.3=pyhff2d567_0
  - font-ttf-dejavu-sans-mono=2.37=hab24e00_0
  - font-ttf-inconsolata=3.000=h77eed37_0
  - font-ttf-source-code-pro=2.038=h77eed37_0
  - font-ttf-ubuntu=0.83=h77eed37_3
  - fontconfig=2.15.0=h1383a14_1
  - fonts-conda-ecosystem=1=0
  - fonts-conda-forge=1=0
  - fonttools=4.60.1=py312h254cc4a_0
  - freetype=2.14.1=hce30654_0
  - fribidi=1.0.16=hc919400_0
  - gdk-pixbuf=2.44.4=h7542897_0
  - glcontext=3.0.0=py312h6b01ec3_2
  - glib=2.86.0=hc66c15f_1
  - glib-tools=2.86.0=hb9d6e3a_1
  - gmp=6.3.0=h7bae524_2
  - graphite2=1.3.14=hec049ff_2
  - h11=0.16.0=pyhd8ed1ab_0
  - h2=4.3.0=pyhcf101f3_0
  - harfbuzz=12.1.0=haf38c7b_0
  - hpack=4.1.0=pyhd8ed1ab_0
  - httpcore=1.0.9=pyh29332c3_0
  - httpx=0.28.1=pyhd8ed1ab_0
  - hyperframe=6.1.0=pyhd8ed1ab_0
  - icu=75.1=hfee45f7_0
  - idna=3.11=pyhd8ed1ab_0
  - importlib-metadata=8.7.0=pyhe01879c_1
  - importlib_resources=6.5.2=pyhd8ed1ab_0
  - ipykernel=6.30.1=py312hca03da5_0
  - ipympl=0.9.7=py312hca03da5_0
  - ipython=9.5.0=py312hca03da5_0
  - ipython_pygments_lexers=1.1.1=py312hca03da5_0
  - ipywidgets=8.1.7=py312hca03da5_0
  - isosurfaces=0.1.2=pyhd8ed1ab_0
  - jaraco.classes=3.4.0=pyhd8ed1ab_2
  - jaraco.context=6.0.1=pyhd8ed1ab_0
  - jaraco.functools=4.3.0=pyhd8ed1ab_0
  - jedi=0.19.2=py312hca03da5_0
  - jinja2=3.1.6=py312hca03da5_0
  - json5=0.9.25=py312hca03da5_0
  - jsonschema=4.25.0=py312hca03da5_0
  - jsonschema-specifications=2023.7.1=py312hca03da5_0
  - jupyter=1.1.1=py312hca03da5_0
  - jupyter-lsp=2.2.5=py312hca03da5_0
  - jupyter_client=8.6.3=py312hca03da5_0
  - jupyter_console=6.6.3=py312hca03da5_1
  - jupyter_core=5.8.1=py312hca03da5_0
  - jupyter_events=0.12.0=py312hca03da5_0
  - jupyter_server=2.16.0=py312hca03da5_0
  - jupyter_server_terminals=0.5.3=py312hca03da5_0
  - jupyterlab=4.4.7=py312hca03da5_0
  - jupyterlab_pygments=0.3.0=py312hca03da5_0
  - jupyterlab_server=2.28.0=py312hca03da5_0
  - jupyterlab_widgets=3.0.15=py312hca03da5_0
  - keyring=25.6.0=pyh534df25_0
  - kiwisolver=1.4.8=py312h313beb8_0
  - lame=3.100=h1a8c8d9_1003
  - lcms2=2.17=h7eeda09_0
  - lerc=4.0.0=hd64df32_1
  - libabseil=20250512.1=cxx17_hd41c47c_0
  - libass=0.17.4=hcbd7ca7_0
  - libblas=3.9.0=38_h51639a9_openblas
  - libcblas=3.9.0=38_hb0561ab_openblas
  - libcxx=21.1.4=hf598326_0
  - libdeflate=1.24=h5773f1b_0
  - libexpat=2.7.1=hec049ff_0
  - libffi=3.5.2=he5f378a_0
  - libfreetype=2.14.1=hce30654_0
  - libfreetype6=2.14.1=h6da58f4_0
  - libgd=2.3.3=hb2c3a21_11
  - libgfortran=15.2.0=hfcf01ff_1
  - libgfortran5=15.2.0=h742603c_1
  - libglib=2.86.0=he69a767_1
  - libhwloc=2.12.1=default_h48b22c3_1002
  - libiconv=1.18=h23cfdf5_2
  - libintl=0.25.1=h493aca8_0
  - libintl-devel=0.25.1=h493aca8_0
  - libjpeg-turbo=3.1.0=h5505292_0
  - liblapack=3.9.0=38_hd9741b5_openblas
  - liblzma=5.8.1=h39f12f2_2
  - libogg=1.3.5=h48c0fde_1
  - libopenblas=0.3.30=openmp_ha158390_2
  - libopenvino=2025.2.0=h56e7ac4_1
  - libopenvino-arm-cpu-plugin=2025.2.0=h56e7ac4_1
  - libopenvino-auto-batch-plugin=2025.2.0=he81eb65_1
  - libopenvino-auto-plugin=2025.2.0=he81eb65_1
  - libopenvino-hetero-plugin=2025.2.0=h273c05f_1
  - libopenvino-ir-frontend=2025.2.0=h273c05f_1
  - libopenvino-onnx-frontend=2025.2.0=h6386500_1
  - libopenvino-paddle-frontend=2025.2.0=h6386500_1
  - libopenvino-pytorch-frontend=2025.2.0=hec049ff_1
  - libopenvino-tensorflow-frontend=2025.2.0=hee62d61_1
  - libopenvino-tensorflow-lite-frontend=2025.2.0=hec049ff_1
  - libopus=1.5.2=h48c0fde_0
  - libpng=1.6.50=h280e0eb_1
  - libprotobuf=6.31.1=h658db43_2
  - librsvg=2.60.0=h5c55ec3_0
  - libsodium=1.0.20=h897f8a9_0
  - libsqlite=3.50.4=h4237e3c_0
  - libtiff=4.7.1=h7dc4979_0
  - libusb=1.0.29=hbc156a2_0
  - libvorbis=1.3.7=h81086ad_2
  - libvpx=1.14.1=h7bae524_0
  - libvulkan-loader=1.4.328.1=h49c215f_0
  - libwebp-base=1.6.0=h07db88b_0
  - libxcb=1.17.0=hdb1d25a_0
  - libxml2=2.15.1=h9329255_0
  - libxml2-16=2.15.1=h0ff4647_0
  - libzlib=1.3.1=h8359307_2
  - llvm-openmp=21.1.4=h4a912ad_0
  - manim=0.19.0=pyh29332c3_0
  - manimpango=0.6.0=py312hbbafe48_0
  - mapbox_earcut=1.0.3=py312h98cfe13_2
  - markdown-it-py=4.0.0=pyhd8ed1ab_0
  - markupsafe=3.0.2=py312h80987f9_0
  - matplotlib=3.10.6=py312hca03da5_0
  - matplotlib-base=3.10.6=py312h066045a_0
  - matplotlib-inline=0.1.7=py312hca03da5_0
  - mdurl=0.1.2=pyhd8ed1ab_1
  - mistune=3.1.2=py312hca03da5_0
  - moderngl=5.11.1=py312h98f7732_1
  - moderngl-window=3.1.1=pyh29332c3_1
  - more-itertools=10.8.0=pyhd8ed1ab_0
  - msgpack-python=1.1.2=py312h84eede6_0
  - nbclient=0.10.2=py312hca03da5_0
  - nbconvert=7.16.6=py312hca03da5_0
  - nbconvert-core=7.16.6=py312hca03da5_0
  - nbconvert-pandoc=7.16.6=py312hca03da5_0
  - nbformat=5.10.4=py312hca03da5_0
  - ncurses=6.5=h5e97a16_3
  - nest-asyncio=1.6.0=py312hca03da5_0
  - networkx=3.5=pyhe01879c_0
  - notebook=7.4.5=py312hca03da5_0
  - notebook-shim=0.2.4=py312hca03da5_0
  - numpy=2.3.4=py312h85ea64e_0
  - openh264=2.6.0=hb5b2745_0
  - openjpeg=2.5.4=hbfb3c88_0
  - openssl=3.5.4=h5503f6c_0
  - overrides=7.4.0=py312hca03da5_0
  - packaging=25.0=pyh29332c3_1
  - pandoc=2.12=hca03da5_3
  - pandocfilters=1.5.1=py312hca03da5_0
  - pango=1.56.4=h875632e_0
  - parso=0.8.4=py312hca03da5_0
  - pbs-installer=2025.10.28=pyhd8ed1ab_0
  - pcre2=10.46=h7125dd6_0
  - pexpect=4.9.0=py312hca03da5_0
  - pillow=12.0.0=py312h16e1670_0
  - pip=25.2=pyh8b19718_0
  - pixman=0.46.4=h81086ad_1
  - pkginfo=1.12.1.2=pyhd8ed1ab_0
  - platformdirs=4.5.0=pyhcf101f3_0
  - poetry=2.1.2=pyh534df25_0
  - poetry-core=2.1.2=pyhd8ed1ab_0
  - prometheus_client=0.21.1=py312hca03da5_0
  - prompt-toolkit=3.0.52=py312hca03da5_1
  - prompt_toolkit=3.0.52=hd3eb1b0_1
  - psutil=7.0.0=py312h254cc4a_0
  - pthread-stubs=0.4=hd74edd7_1002
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pugixml=1.15=hd3d436d_0
  - pure_eval=0.2.3=py312hca03da5_0
  - pycairo=1.28.0=py312h0012f17_1
  - pycparser=2.22=pyh29332c3_1
  - pydub=0.25.1=pyhd8ed1ab_1
  - pyglet=2.1.9=pyhd8ed1ab_0
  - pyglm=2.8.2=py312ha0dd364_1
  - pygments=2.19.2=pyhd8ed1ab_0
  - pyobjc-core=12.0=py312h19bbe71_1
  - pyobjc-framework-cocoa=12.0=py312h1de3e18_1
  - pyparsing=3.2.0=py312hca03da5_0
  - pyproject_hooks=1.2.0=pyhd8ed1ab_1
  - pysocks=1.7.1=pyha55dd90_7
  - python=3.12.12=h18782d2_1_cpython
  - python-build=1.3.0=pyhff2d567_0
  - python-dateutil=2.9.0post0=py312hca03da5_2
  - python-fastjsonschema=2.21.2=pyhe01879c_0
  - python-installer=0.7.0=pyhff2d567_1
  - python-json-logger=3.2.1=py312hca03da5_0
  - python_abi=3.12=8_cp312
  - pyyaml=6.0.3=py312h5748b74_0
  - pyzmq=27.1.0=py312h854a7ef_0
  - qtconsole=5.7.0=py312hca03da5_0
  - qtpy=2.4.3=py312hca03da5_0
  - rapidfuzz=3.14.1=py312h455b684_0
  - readline=8.2=h1d1bf99_2
  - referencing=0.30.2=py312hca03da5_0
  - requests=2.32.5=pyhd8ed1ab_0
  - requests-toolbelt=1.0.0=pyhd8ed1ab_1
  - rfc3339-validator=0.1.4=py312hca03da5_0
  - rfc3986-validator=0.1.1=py312hca03da5_0
  - rich=14.2.0=pyhcf101f3_0
  - rpds-py=0.22.3=py312h2aea54e_0
  - scipy=1.16.3=py312ha6bbf71_0
  - screeninfo=0.8.1=py312h81bd7bf_3
  - sdl2=2.32.56=h248ca61_0
  - sdl3=3.2.24=h919df07_0
  - send2trash=1.8.2=py312hca03da5_1
  - setuptools=80.9.0=pyhff2d567_0
  - shellingham=1.5.4=pyhd8ed1ab_1
  - six=1.17.0=py312hca03da5_0
  - skia-pathops=0.8.0.post2=py312ha0dd364_1
  - snappy=1.2.2=hd121638_0
  - sniffio=1.3.1=pyhd8ed1ab_1
  - soupsieve=2.8=pyhd8ed1ab_0
  - srt=3.5.3=pyhd8ed1ab_1
  - stack_data=0.6.3=py312hca03da5_0
  - svgelements=1.9.6=pyhd8ed1ab_0
  - svt-av1=3.1.2=h12ba402_0
  - tbb=2022.2.0=h5b2e6d4_1
  - terminado=0.18.1=py312hca03da5_0
  - tinycss2=1.4.0=py312hca03da5_0
  - tk=8.6.13=h892fb3f_2
  - tomli=2.3.0=pyhcf101f3_0
  - tomlkit=0.13.3=pyha770c72_0
  - tornado=6.5.1=py312h80987f9_0
  - tqdm=4.67.1=pyhd8ed1ab_1
  - traitlets=5.14.3=py312hca03da5_0
  - trove-classifiers=2025.9.11.17=pyhd8ed1ab_0
  - typing-extensions=4.15.0=h396c80c_0
  - typing_extensions=4.15.0=pyhcf101f3_0
  - tzdata=2025b=h78e105d_0
  - urllib3=2.5.0=pyhd8ed1ab_0
  - virtualenv=20.35.4=pyhd8ed1ab_0
  - watchdog=6.0.0=py312h163523d_1
  - wcwidth=0.2.13=py312hca03da5_0
  - webencodings=0.5.1=py312hca03da5_2
  - websocket-client=1.8.0=py312hca03da5_0
  - wheel=0.45.1=pyhd8ed1ab_1
  - widgetsnbextension=4.0.14=py312hca03da5_0
  - x264=1!164.3095=h57fd34a_2
  - x265=3.5=hbc6ce65_3
  - xattr=1.3.0=py312hdb5c506_0
  - xorg-libxau=1.0.12=h5505292_0
  - xorg-libxdmcp=1.1.5=hd74edd7_0
  - yaml=0.2.5=h925e9cb_3
  - zeromq=4.3.5=h2c7f8f0_1
  - zipp=3.23.0=pyhd8ed1ab_0
  - zlib-ng=2.2.5=hf787086_0
  - zstandard=0.25.0=py312h37e1c23_0
  - zstd=1.5.7=h6491c7d_2
prefix: /opt/miniconda3/envs/fp5300
